// packages/angular/demo/app.component.ts
import { Component } from '@angular/core';
import { AccessibilityPanelComponent } from '@accesspath/angular';

const STORAGE_KEY = 'accesspath-angular-demo';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [AccessibilityPanelComponent],
  template: `
    <div class="page">
      <header>
        <h1>AccessPath — Angular demo</h1>
        <div class="actions">
          <button type="button" (click)="isDarkTheme = !isDarkTheme">
            {{ isDarkTheme ? 'Light theme' : 'Dark theme' }}
          </button>
          <button type="button" (click)="a11yPanel.open()">Open accessibility panel</button>
        </div>
      </header>

      <main>
        <h2>Sample content</h2>
        <p>Toggle a preference in the panel and watch this page change.</p>
        <p><a href="https://angular.dev">A sample link</a>, to try Highlight Links.</p>
        <img
          src="https://angular.io/assets/images/logos/angular/angular.svg"
          width="80"
          alt="Angular logo"
        />
      </main>

      <app-accessibility-panel
        #a11yPanel
        [isDarkTheme]="isDarkTheme"
        [storageKey]="storageKey"
      ></app-accessibility-panel>
    </div>
  `,
  styles: [
    `
      .page { font-family: system-ui, sans-serif; padding: 16px; }
      header { display: flex; justify-content: space-between; align-items: center; }
      .actions { display: flex; gap: 8px; }
      main { margin-top: 16px; padding: 16px; border: 1px solid #e2e2ea; border-radius: 12px; }
    `,
  ],
})
export class AppComponent {
  isDarkTheme = false;
  readonly storageKey = STORAGE_KEY;
}

// packages/react/demo/App.tsx
import { useRef, useState } from 'react';
import { AccessPathPanel, useAccessPath } from '@accesspath/react';
import type { AccessPathPanelHandle } from '@accesspath/react';

const STORAGE_KEY = 'accesspath-react-demo';

export function App() {
  const panelRef = useRef<AccessPathPanelHandle>(null);
  const [container, setContainer] = useState<HTMLElement | null>(null);
  const [isDarkTheme, setIsDarkTheme] = useState(false);
  const { prefs } = useAccessPath(STORAGE_KEY);

  return (
    <div style={{ fontFamily: 'system-ui, sans-serif' }}>
      <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: 16 }}>
        <h1>AccessPath — React demo</h1>
        <div style={{ display: 'flex', gap: 8 }}>
          <button type="button" onClick={() => setIsDarkTheme((v) => !v)}>
            {isDarkTheme ? 'Light theme' : 'Dark theme'}
          </button>
          <button type="button" onClick={() => panelRef.current?.open()}>
            Open accessibility panel
          </button>
        </div>
      </header>

      <div
        ref={setContainer}
        className="a11y-target"
        style={{
          position: 'relative',
          margin: 16,
          padding: 16,
          minHeight: 420,
          borderRadius: 12,
          background: isDarkTheme ? '#1a1a2e' : '#fff',
          color: isDarkTheme ? '#fff' : '#111',
          border: '1px solid #e2e2ea',
        }}
      >
        <p>Hello! What are you craving today?</p>
        <p>Current text size preference: {prefs.fontSize}</p>

        <AccessPathPanel
          ref={panelRef}
          container={container}
          isDarkTheme={isDarkTheme}
          storageKey={STORAGE_KEY}
        />
      </div>
    </div>
  );
}
